language: python

install:
  - pip install pylint netdata

before_script:
  - pylint --version

script:
  - pylint  --variable-naming-style=any --disable=too-few-public-methods, missing-docstring dump1090.chart.py
