language: python
python:
  - "2.7"
  - "3.6"

cache: pip

install:
  - pip install pylint netdata

before_script:
  - pylint --version

script:
  - pylint  --variable-naming-style=any --argument-naming-style=any --disable=too-few-public-methods,C0111 dump1090.chart.py
  - pylint  --variable-naming-style=any --argument-naming-style=any --disable=too-few-public-methods,C0111 dump978.chart.py
