language: python
cache: pip

install:
  - pip install pylint netdata

before_script:
  - pylint --version

script:
  - pylint  --variable-naming-style=any --argument-naming-style=any --disable=too-few-public-methods,C0111 dump*.chart.py
